// invitados.js
window.invitados = [
  { id: 1, nombre: "Familia Bätzel Mejía", pases: 3 },
  { id: 2, nombre: "María Luz Echarres", pases: 1 },
  { id: 3, nombre: "Juan Pablo Mejía Echarres", pases: 2 },
  { id: 4, nombre: "Familia Cardona Morales", pases: 4 },
  { id: 5, nombre: "Señorita Paola Cardona", pases: 1 },
  { id: 6, nombre: "Familia Vides Mejía", pases: 3 },
  { id: 7, nombre: "Familia Guzmán Mejía", pases: 2 },
  { id: 8, nombre: "Familia Mejía Godoy", pases: 4 },
  { id: 9, nombre: "Familia Mejía González", pases: 2 },
  { id: 10, nombre: "Señora Sylvia María Paz González", pases: 1 },
  { id: 11, nombre: "Familia Mejía Paredes", pases: 2 },
  { id: 12, nombre: "Hermanos Mejía Rodríguez", pases: 3 },
  { id: 13, nombre: "Señora Albita Coronado y Marleny Mejía", pases: 2 },
  { id: 14, nombre: "Familia Mejía Gómez", pases: 2 },
  { id: 15, nombre: "Señor Willy Estuardo Mejía Paredes", pases: 1 },
  { id: 16, nombre: "Familia Paz González", pases: 2 },
  { id: 17, nombre: "Familia Rivas Castillo", pases: 3 },
  { id: 18, nombre: "Señor Pedro Pablo Rivas Castillo", pases: 1 },
  { id: 19, nombre: "Milvia", pases: 1 },
  { id: 20, nombre: "Señora Yolanda Quijivix e hija", pases: 2 },
  { id: 21, nombre: "Señor Carlos Mejía", pases: 1 },
  { id: 22, nombre: "Licenciada Claudia Lorena Roldán", pases: 1 },
  { id: 23, nombre: "Licenciada Claudia Michelle Uceda Castro", pases: 1 },
  { id: 24, nombre: "Señores Carlos Camas y Jorge Zayas", pases: 2 },
  { id: 25, nombre: "Familia España Cruz", pases: 2 },
  { id: 26, nombre: "Familia Muy Pineda", pases: 3 },
  { id: 27, nombre: "Familia Bustamante Pamal", pases: 2 },
  { id: 28, nombre: "Familia García-Salas Santaluce", pases: 2 },
  { id: 29, nombre: "Señora Annie Caravantes", pases: 1 },
  { id: 30, nombre: "Familia Pineda Mazariegos", pases: 2 },
  { id: 31, nombre: "Familia Leal Alvarado", pases: 2 },
  { id: 32, nombre: "Licenciado Miguel Retolaza y esposa", pases: 2 },
  { id: 33, nombre: "Familia Ramírez Alvarez", pases: 2 },
  { id: 34, nombre: "Señorita Claudia Scaglia", pases: 1 },
  { id: 35, nombre: "Señor Joe Koplowitz y esposa", pases: 2 },
  { id: 36, nombre: "Familia Vásquez Garcia", pases: 2 },
  { id: 37, nombre: "Señora Elida Florinda Echarrez", pases: 2 },
  { id: 38, nombre: "Familia Aguilar Velásquez", pases: 3 },
  { id: 39, nombre: "Licenciado Martín Carias Uceda", pases: 2 },
  { id: 40, nombre: "Licenciada Isabel Zenteno Roldán", pases: 2 },
  { id: 41, nombre: "Licenciada Rina Méndez Rabe", pases: 1 },
  { id: 42, nombre: "Licenciado Otto Melgar y esposa", pases: 3 },
  { id: 43, nombre: "Licenciado Edgar Melgar y esposa", pases: 2 },
  { id: 44, nombre: "Señora Irma Eleida Echarry e hijas", pases: 3 },
  { id: 45, nombre: "Señora Thelma Mejía", pases: 1 },
  { id: 46, nombre: "Familia López Rendon", pases: 2 },
  { id: 47, nombre: "Licenciado Victor Lucas", pases: 2 },
  { id: 48, nombre: "Licenciada Paola Urquizú", pases: 2 },
  { id: 49, nombre: "Licenciada Jennifer Lessing", pases: 2 },
  { id: 50, nombre: "Señor Joe Soteldo", pases: 1 },
  { id: 51, nombre: "Señora Wendy Concretras e hijos", pases: 3 },
  { id: 52, nombre: "Marisol Barrientos", pases: 1 },
  { id: 53, nombre: "Mia Caravantes", pases: 1 },
  { id: 54, nombre: "Luis Juarez", pases: 1 },
  { id: 55, nombre: "Andrés Rodas", pases: 1 },
  { id: 56, nombre: "Vania Sagastume", pases: 1 },
  { id: 57, nombre: "Marcela Del Aguila", pases: 1 },
  { id: 58, nombre: "Camila Vasquez", pases: 1 },
  { id: 59, nombre: "Brihana Lopez", pases: 1 },
  { id: 60, nombre: "Javier Aquino", pases: 1 },
  { id: 61, nombre: "Sebastian Polanco", pases: 1 },
  { id: 62, nombre: "Javier Orozco", pases: 1 },
  { id: 63, nombre: "Zully Monterroso", pases: 1 },
  { id: 64, nombre: "Ronal Alvarez", pases: 1 },
  { id: 65, nombre: "Caleb Dubon", pases: 1 },
  { id: 66, nombre: "Fernando Lopez", pases: 1 },
  { id: 67, nombre: "Juan Diego Pape", pases: 1 },
  { id: 68, nombre: "Santiago Aguilar", pases: 1 },
  { id: 69, nombre: "Isabella Ávila", pases: 1 },
  { id: 70, nombre: "Sebastián Barrios", pases: 1 },
  { id: 71, nombre: "Ian Cazali", pases: 1 },
  { id: 72, nombre: "Luis Padilla", pases: 1 },
  { id: 73, nombre: "Álvaro Hurtarte", pases: 1 },
  { id: 74, nombre: "Pablo Cordon", pases: 1 },
  { id: 75, nombre: "Isabella Sandoval", pases: 1 },
  { id: 76, nombre: "Santiago Alí", pases: 1 },
  { id: 77, nombre: "Dylan Marin", pases: 1 },
  { id: 78, nombre: "Rebeca Flores", pases: 1 },
  { id: 79, nombre: "Sofía Cardona", pases: 1 },
  { id: 80, nombre: "Dulce Canton", pases: 1 },
  { id: 81, nombre: "Paula Gómez", pases: 1 },
  { id: 82, nombre: "Jorge Ramírez", pases: 1 },
  { id: 83, nombre: "Matilde Gonzalez", pases: 1 },
  { id: 84, nombre: "Licenciada Susana Mejía", pases: 2 },
  { id: 85, nombre: "Señora Rosa Leiva e hija", pases: 3 },
  { id: 86, nombre: "Licenciada Marilyn Arévalo", pases: 1},
  { id: 87, nombre: "Señora Juana María Antonio Guerra", pases: 1 }
];

